# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efc594a0b7faf91ed1e96eb9b21931176f78a69d374cbb6aff932fc8818a1b5917e318a230f21e21b58194dbfab8e0de2abc44e0923595d4f57c5f47ee7f9f00

test:
  secret_key_base: 1c949beaef75546fb2a4e63497adb53882ed8f43a3ac82fc3c88fca672188222e9c02dd9de020927c6d80202600a83196ce7b9d3c329c3643fc7f1733df219b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
